### ISSUE TITLE
TabBar disappears once I use a segue. TableView won't reload when using modal

### ISSUE THREAD

**Issue by LarryBrian** [Yalantis/FoldingTabBar.iOS#15]
I have VC1 with a tableview. Once I click the left tab bar button it goes to VC2 with a tableview using a segue, but once I click "back" button in VC2 using a segue the tab Bar disappears for VC1. Instead i used the [self dismissviewcontroller....] method and the VC1 comes up just fine with the tab bar except the tableview will not reload with the updated data from VC2. I already tried to place [tableview reloadData] in viewWillAppear method and it still is not working. 

How can I fix this issue?

**Comment by sheyoshida** [comment]
My tab bar was vanishing when I navigated away from it too - it is an easy fix, just wrap your view controller in a navigation controller like this: 

<img width="508" alt="screen shot 2015-10-15 at 12 35 31 pm" src="https://cloud.githubusercontent.com/assets/12483412/10520649/47989c04-7339-11e5-8d4d-e47d24896ab3.png">

**Comment by serejahh** [comment]
@LarryBrian Have you tried the solution above? Do you need some help?

**Comment by nasseryacout** [comment]
i have a similar issue, i implement my view hierarchy like the solution above, when i push my view controller  the tabar works fine, but when i hit back the tabbar  collapsed and not response to any thing.

i added a caption text below the buttons, and in addition the text appear at the bottom of the screen and is isolated from the tabbar button.

any help in this issue?

**Comment by nyxee** [comment]
In addition to using a Navigation Controller, you also need to use unwind segues (methods with the signature``` @IBAction func methodname(_ segue:)```) which are implemented in the source view controller. Secondly, from the destination View Controller, control-click from the navigation bar button to the Exit object above the view controller then pick the correct action name from the popup menu.  The unwind segue will be accessible from the Document Outline and can be given an identifier to use in ```prepare(for:sender:)``` in case data needs to be sent to the from the destination view controller.
