### ISSUE TITLE
How to use folding tab bar on none root view controller?

### ISSUE THREAD

**Issue by MarceloPrado** [Yalantis/FoldingTabBar.iOS#18]
Hello, how are you doing today?
I'm trying to set YALFoldingTabBarController on specific view controller inside App Delegate, but it doesn't work (tab bar doesn't show up). It is possible to use this tab bar outside root view controller? How?
Thanks!

**Comment by scoobydont** [comment]
I was stuck on this for a bit but this is how I got it to work:

First, in your main storyboard, make a new UITabBarController. Next, add a new Cocoa Touch Class file to your project and make sure it is a subclass of YALFoldingTabBarController. Whatever you end up naming it, go back to the main storyboard and set the class name of the UITabBarController you made earlier to the name you gave to the Cocoa Touch Class file you created.

Next, in the new class file you made in the viewDidLoad function, you would set up all the same things you see in the AppDelegate file in the example provided by Yalantis minus this statement:

YALFoldingTabBarController *tabBarController = (YALFoldingTabBarController *) self.window.rootViewController;

Then, everytime you see tabBarController used, you would simple use "super" instead. This worked for me using swift so the SampleFoldingTabBarController.swift file (which is the custom Cocoa Touch Class I made) looks something like this:

```
import UIKit
import FoldingTabBar

class SampleFoldingTabBarController: YALFoldingTabBarController {

let tabItem1: YALTabBarItem = YALTabBarItem(itemImage: UIImage(named:"something", leftItemImage: UIImage(named:"somethingElse")

override func viewDidLoad() {

    super.viewDidLoad()

    super.leftBarItems = [tabItem1]

    super.centerButtonImage = UIImage(named: "centerImage")

    //so on and so forth

}
```

**Comment by serejahh** [comment]
@MarceloPrado Have you tried the solution above? Do you need some help?

**Comment by alexrodrigues** [comment]
It works!!! Thanks

**Comment by LiveRock** [comment]
It works! But I also want to handle touches on extra tabBarItems in the items page. So far, no successes after 2 days...

`import Foundation
import UIKit
import ARSLineProgress
import FoldingTabBar

class ViewControllerHome: UIViewController,UITextFieldDelegate,YALTabBarInteracting,YALTabBarViewDelegate {

```
var delegate: YALTabBarViewDelegate?

override func viewDidLoad() {
    super.viewDidLoad()
    print("Home VC called")
    // Do any additional setup after loading the view.


  //  tabBarController = (YALFoldingTabBarController *) self.window.rootViewController

}

// MARK: YALTabBarInteracting protocol
@objc func extraLeftItemDidPressInTabBarView(tabBar: YALFoldingTabBar) {
    print("extraLeftItemDidPressed")

}

@objc func extraRightItemDidPressed(sender: AnyObject) {
    print("extraRightItemDidPressed")

}
```

}`

**Comment by LiveRock** [comment]
Ok, i got it.

**Comment by hungri-yeti** [comment]
@LiveRock Can you give some guidance how you did this?

**Comment by LiveRock** [comment]
First, you need to conform to the protocol YALTabBarInteracting
Then you need to implement extraLeftItemDidPress and extraRightItemDidPress like this:

  // MARK: YALTabBarInteracting protocol
    @objc func extraLeftItemDidPress() {
        print("extraLeftItemDidPress")  
    }

I couldn't get it to work initially because I did not implement it properly like:
    @objc func extraLeftItemDidPress(sender : AnyObject!) {
        print("extraLeftItemDidPress")  
    }

**Comment by tambadiya** [comment]
I am ios developer..
i want to use folding tabbar in only one view controller so its possible for use it..?

**Comment by ilhammalik** [comment]
i want implement for swift, some people can help me?

**Comment by pythlang** [comment]
hey, guys, I really need some help instantiating this in Swift. 

a setp-by-step would really go a long way. please explain it like i'm 5 because that's what i feel like right now trying to get this thing to work.

The code the @scoobydont provided isn't complete and it's giving me errors; i'm pretty new to doing these animations in Swift. Everything seems set up fine with the bridging headers etc but I cannot seem to get this to work for the life of me. 

thanks.
