### ISSUE TITLE
English Spelling Error in View's Header Files #naming issue

### ISSUE THREAD

**Issue by lastcc** [Yalantis/FoldingTabBar.iOS#19]
- (void)tabBarViewDidCollapsed:(YALFoldingTabBar *)tabBarView;
- (void)tabBarViewDidExpanded:(YALFoldingTabBar *)tabBarView;
- (void)extraLeftItemDidPressedInTabBarView:(YALFoldingTabBar *)tabBarView;
- (void)extraRightItemDidPressedInTabBarView:(YALFoldingTabBar *)tabBarView;

I think, it should be DidCollapse, instead of DidCollapsed, because there is "did" and we don't use -ed after "did."

Like, it is "applicationDidEnterBackgroound" and not "DidEnteredBackground."

**Comment by maksym-letiushov** [comment]
@lastcc thanks
