### ISSUE TITLE
Is it possible to change the background color of tabBar to transparent?

### ISSUE THREAD

**Issue by weinanfeng** [Yalantis/FoldingTabBar.iOS#25]
![trivial](https://cloud.githubusercontent.com/assets/12074304/10937436/16e584ea-82f3-11e5-9afb-51ff000039f7.jpg)

Under tabBar, the color is purple. Is it possible to change the purple background color to transparent that user can see content (in this case the pink color) under tabBar?

**Comment by IgorMuzyka** [comment]
@weinanfeng, absolutely. First you need this two imports in `viewController` where you want to change `backgroundColor` of `tabBar`.

``` objective-c
#import "YALFoldingTabBarController.h"
#import "YALFoldingTabBar.h"
```

And then in that same `viewController`:

``` objective-c
YALFoldingTabBarController *controller = (YALFoldingTabBarController *)self.tabBarController;
YALFoldingTabBar *tabBar = controller.tabBarView;
tabBar.backgroundColor = [UIColor preferredColor];
```

**Comment by rickyjwhong** [comment]
Hello,

I tried doing this with the [UIColor clearColor] but only end up getting a partially gray transparent background color. Any idea why?

**Comment by weinanfeng** [comment]
@IgorMuzyka Thanks a lot! Works perfectly.

**Comment by harrymelka** [comment]
Hello,

I tried to do it with swift, didn't work :s,
Did you have any idea with it ?
Thank you
