### ISSUE TITLE
iOS7 support?

### ISSUE THREAD

**Issue by lopezjurip** [Yalantis/FoldingTabBar.iOS#3]
It is possible to add support for iOS7?

**Comment by maksym-letiushov** [comment]
Definitely it's possible !!! We can add iOS 7 support, but I don't know when we have time to do it. We are open for pull requests. Thank you.

**Comment by art-divin** [comment]
I was able to run the project in iOS Simulator with iOS 7.1 without any modifications.

**Comment by maksTheAwesome** [comment]
Well I think this issue can be closed now. Thank you art-divin.

**Comment by serejahh** [comment]
@maximletushov, I've tested on Simulator (iOS 7.0) and it works perfectly. Have you got some trouble on a device?

**Comment by maksym-letiushov** [comment]
Resolved by #22 
Thanks
