### ISSUE TITLE
Update Left / Right Extra Buttons based on Action

### ISSUE THREAD

**Issue by DonBaronFactory** [Yalantis/FoldingTabBar.iOS#30]
How would I proceed to say update (hide, change icon) of an Left / Right Extra button after a user has for example logged in the app... In case the user is logged out, I would like to hide the Logout button, while display it when the user is logged in... Thanks for your help

**Comment by serejahh** [comment]
Hi @cre8it. Thanks for your interest to our component.
For now it can't be done, but I can add the feature. Please, tell me if it's needed for you

**Comment by hyerra** [comment]
I needed the same functionality so I created a pull request: https://github.com/Yalantis/FoldingTabBar.iOS/pull/60

Hope it helps!

**Comment by serejahh** [comment]
Done in #60
