### ISSUE TITLE
Swift implementation.

### ISSUE THREAD

**Issue by SketchySwift** [Yalantis/FoldingTabBar.iOS#42]
In the documentation(right here on github) that teaches on how to use it, Can you guys please also tell us how to use it with swift.

**Comment by SebastianBO** [comment]
Would love this!! Can't express this enough

**Comment by juniorProgrammer** [comment]
What you would do is import FoldingTabBar into the file that you are using it for and everything from there is pretty much the same as objective c. I had problems also trying to figure out how to implement it and this way worked best for me. Hope this help

**Comment by PravdaEvgen** [comment]
add Swift manuals
