### ISSUE TITLE
How to set Badge Value on TabBarItem

### ISSUE THREAD

**Issue by syedqamara** [Yalantis/FoldingTabBar.iOS#43]
I have 4 items in my FoldingTabBarController but i want to set badge value to one of them which is at index 2.
I can't understand how to do this? 
Can you please quote an Example?

**Comment by serejahh** [comment]
Hi @syedqamara. Thanks for your interest to our component.
For now it can't be done, but I can add the feature. Please, tell me if it's needed for you

**Comment by IgorMuzyka** [comment]
@syedqamara you can found the view you interested in tabBar.subviews and then add a badge to it

**Comment by asar1** [comment]
Did anybody achieved this functionality yet?

**Comment by jaypanchal12** [comment]
@IgorMuzyka can u please explain a bit more.
