### ISSUE TITLE
Make tab bar always expand 

### ISSUE THREAD

**Issue by vietnguyen09** [Yalantis/FoldingTabBar.iOS#44]
Hi there,

First of all, thanks for your hard working and share your work to the world.

How can I make your tab bar always expand?

Thanks

**Comment by PravdaEvgen** [comment]
You mean always expand on start?

**Comment by serejahh** [comment]
Hi @vietnguyen09 
I'm sorry, but it's impossible to do. The idea of the component is hide tabbar and show additional buttons. If the tabbar always is expanded there will be a space in the middle of the tabbar and the tabbar won't be foldable
