### ISSUE TITLE
Swift - Cannot get Items Pressed even with conforming YALTabBarViewDelegate

### ISSUE THREAD

**Issue by repixels** [Yalantis/FoldingTabBar.iOS#45]
We have two issues after inserting The Folding Tab Bar
1. The Tab Bar Life cycle functions and the extra button items aren't triggered
2. The tab bar isn't curved

![simulator screen shot may 6 2016 8 30 06 pm](https://cloud.githubusercontent.com/assets/14933467/15082663/573ffb08-13c9-11e6-9436-8d3328bbdba9.png)

**Comment by LiveRock** [comment]
Me too. I am using Swift and in my UIViewController, I already subscribed to both YALTabBarInteracting,YALTabBarViewDelegate.

I am not getting any responses from extraLeftItemDidPressInTabBarView or extraRightItemDidPressed.

HELP!

**Comment by PravdaEvgen** [comment]
Check our update))
