### ISSUE TITLE
TabBarViewController delegate

### ISSUE THREAD

**Issue by balkarov** [Yalantis/FoldingTabBar.iOS#5]
Hello! 
How to call this method 
- (BOOL)tabBarController:(UITabBarController *)tabBarController shouldSelectViewController:(UIViewController *)viewController 
  
  to trigger animations between controllers?

**Comment by maksTheAwesome** [comment]
Runia, I've added I've created the pull request that fixes the problem. If you do not have time to wait update the "itemInTabBarViewPressed" method in YALFoldingTabBarController with the following code: 

``` objective-c
- (void)itemInTabBarViewPressed:(YALFoldingTabBar *)tabBarView atIndex:(NSUInteger)index {
    BOOL should = YES;
    if ([self.delegate respondsToSelector:@selector(tabBarController:shouldSelectViewController:)]) {
        should = [self.delegate tabBarController:self shouldSelectViewController:[self.viewControllers objectAtIndex:index]];
    }
    if (should) {
        self.selectedViewController = [self.viewControllers objectAtIndex:index];
    }

}
```

**Comment by IgorMuzyka** [comment]
This fix #11  now included in master so until next version is released if you use your pod like

```
pod 'FoldingTabBar', :git => 'https://github.com/Yalantis/FoldingTabBar.iOS.git'
```

you'll have this method.
Will release a new version a bit later

**Comment by avicooper1** [comment]
Since I only started programming iOS in Swift, I am not really sure how to use the above method by @maksTheAwesome How can I access the `Bool should` value so that I can prevent switching?
Thanks

**Comment by avicooper1** [comment]
To be more specific, I would like to control whether or not the tabBar actually switches. I would like to cancel the switch but keep the index of the selected barButtonItem. Then when an asynchronous network call finishes, recall the `shouldSelectViewController` with the previously stored index.
