### ISSUE TITLE
TabBarView Datasource and Delegate

### ISSUE THREAD

**Issue by loicgriffie** [Yalantis/FoldingTabBar.iOS#57]
Hi,

Is it possible to rollback the 2 following properties in order to be able to use the TabBarView without the use of the TabBarController if not wanted ?

```
public class YALFoldingTabBar : UIView {
  @IBOutlet weak public var dataSource: YALTabBarDatasource!
  @IBOutlet weak public var delegate: YALTabBarDelegate!
  [...]
}
```

**Comment by serejahh** [comment]
Hi @Appsido. Sure, It's been updated in v. 1.0.7, please update

Also check out our new animation: https://github.com/Yalantis/ColorMatchTabs

**Comment by loicgriffie** [comment]
You rocks !
