### ISSUE TITLE
Sample App and Integrated App crashes when entering foreground

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [Yalantis/FoldingTabBar.iOS#59]
App crashes when entering foreground. Works fine if i don't switch to any other view controllers but if i switch to a view controller other than the initial one presented it crashes when entering foreground from background. Never reaches the app delegate function  "applicationWillEnterForeground(application: UIApplication)"

Sample app provided crashes using FoldingTabBar
Custom app crashes using FoldingTabBar

Error Code: **\* -[Not A Type CA_copyRenderValue]: message sent to deallocated instance 0x141241830

Specs:
Using version 'FoldingTabBar', '~> 1.0.7'
Apple Swift version 2.2 (swiftlang-703.0.18.8 clang-703.0.31)
I have the latest version of CocaoaPods - cocoapods-1.0.0
Swift Project with Bridging Header
Iphone 6 Software Version 9.1

![image](https://cloud.githubusercontent.com/assets/14100765/17601268/de906468-5fcc-11e6-9a8e-70bfb0b3f14b.png)

![image](https://cloud.githubusercontent.com/assets/14100765/17594909/822f6e10-5fb0-11e6-85d4-25afc9898c44.png)

**Comment by benjaminLedel** [comment]
Workaround (if you don't using new features)

`'FoldingTabBar', '~> 1.0.6'`

**Comment by imanodaysoffdotcom** [comment]
When i enter pod 'FoldingTabBar', '~> 1.0.6' that into my pod file it still downloads the version 1.0.7...... I even tried 1.0.5

**Comment by imanodaysoffdotcom** [comment]
I also did a manual installation of version 1.0.6 and the app still crashes when returning to the foreground.

**Comment by serejahh** [comment]
Hi @imanodaysoffdotcom, @schuleplus! Thanks for reporting the issue. It's fixed in a new release
