### ISSUE TITLE
how to hide navigation Bar when using more than 4 view controller

### ISSUE THREAD

**Issue by vishw3** [Yalantis/FoldingTabBar.iOS#6]
hi i have to present 6 view controller in tabbarcontroller and every thing is fine except i will get navigation controller when select 5 th and 6th view controller how to hide it

**Comment by EugeneEl** [comment]
Hello, thank you for paying attention to our control and your question.
Yes, we are going to implement it in the next update (is coming soon).

**Comment by rahulskh** [comment]
How to hide tabbarcontroller when pushed? I am trying .hidesBottomBarWhenPushed = YES but no luck.
Thanks!

**Comment by SoXeon** [comment]
If you use custom tabbar, you can post notification when you push or pop view controller

**Comment by ortizroberto** [comment]
Guys I'm loving this control, it would awesome if the left and right items could be connected to other view controllers, because I also need more than 4 view controllers. Thanks !!
