### ISSUE TITLE
Tab Bar Extra Item and Main Button Change Color to Blue on UIalertviewController appearance

### ISSUE THREAD

**Issue by imanodaysoffdotcom** [Yalantis/FoldingTabBar.iOS#61]
Whenever i open up a uialertcontroller the color of the middle button and extra buttons change to blue. 

I set the color in the app delegate and do not change it throughout the entire app so it's strange this is happening

**Comment by serejahh** [comment]
hi @imanodaysoffdotcom 

I presented an alert and nothing happened:
![simulator screen shot 30 aug 2016 10 38 55](https://cloud.githubusercontent.com/assets/2575555/18080417/2b858bba-6e9e-11e6-9ca7-91ce4ce50aa3.png)

Could you provide some details?

**Comment by imanodaysoffdotcom** [comment]
Notice the menu button

Before 
![image1 1](https://cloud.githubusercontent.com/assets/14100765/18817106/d622597a-831d-11e6-9d24-35749e2d8f89.PNG)
During 
![image2](https://cloud.githubusercontent.com/assets/14100765/18817108/db455f1a-831d-11e6-9927-c34502c3e49e.PNG)
After
![image3](https://cloud.githubusercontent.com/assets/14100765/18817109/e0af3a52-831d-11e6-82dd-2b677cbc8468.PNG)


The Extra buttons on the right and left also do the same. they are also blue

**Comment by imanodaysoffdotcom** [comment]
Notice the menu button color

Before
![img_1010](https://cloud.githubusercontent.com/assets/14100765/18817137/d5a87a96-831e-11e6-9d30-149e7de620ba.PNG)

During
![img_1012](https://cloud.githubusercontent.com/assets/14100765/18817140/f72511b6-831e-11e6-8db6-6e61a421c290.PNG)

After 

![img_1011](https://cloud.githubusercontent.com/assets/14100765/18817142/fcb540a6-831e-11e6-9196-38bf18e32061.PNG)

**Comment by imanodaysoffdotcom** [comment]
i tried to change the profile picture which produced the menu you see in the 2nd screenshot

**Comment by serejahh** [comment]
Thanks for the screenshots. I'l investigate the issue

**Comment by serejahh** [comment]
What property do you change in the app delegate? I've created a branch: https://github.com/Yalantis/FoldingTabBar.iOS/tree/feature/61. Please, pull it, run and select a row in the chat

**Comment by imanodaysoffdotcom** [comment]
in my app delegate here is my setuop function.  I do not make any changes to the folding tab bar throughout the app

func setupCustomTabBar() {
        tabBarController = self.window?.rootViewController as! YALFoldingTabBarController

```
    let item1: YALTabBarItem = YALTabBarItem(itemImage: UIImage(named: "Home"), leftItemImage:  UIImage(named: "SynchronizeFilled"), rightItemImage: UIImage(named: "Meeting-Non-Filled"))

    //UIImage(named: "UninstallingUpdates") - upload lst pymt btn
    let item2: YALTabBarItem = YALTabBarItem(itemImage: UIImage(named: "Donate"), leftItemImage: nil, rightItemImage: nil)
    tabBarController.leftBarItems = [item1,item2]


    let item3: YALTabBarItem = YALTabBarItem(itemImage: UIImage(named: "KGS4.png"), leftItemImage: UIImage(named: "edit_icon"), rightItemImage: UIImage(named: "SynchronizeFilled"))
    let item4: YALTabBarItem = YALTabBarItem(itemImage: UIImage(named: "settings_icon"), leftItemImage: nil, rightItemImage: nil)

    tabBarController.rightBarItems = [item3, item4]

    tabBarController.centerButtonImage = UIImage(named: "plus_icon")
    tabBarController.selectedIndex = 0

    //customize tabBarView
    tabBarController.tabBarView.backgroundColor = UIColor.livoBeigeColor()
    tabBarController.tabBarView.tabBarColor = UIColor.livoOrangeColor()
    tabBarController.tabBarView.dotColor = UIColor.whiteColor()


    tabBarController.tabBarView.extraTabBarItemHeight = YALExtraTabBarItemsDefaultHeight
    tabBarController.tabBarView.tabBarViewEdgeInsets = YALTabBarViewHDefaultEdgeInsets
    tabBarController.tabBarView.tabBarItemsEdgeInsets = YALTabBarViewItemsDefaultEdgeInsets
    tabBarController.tabBarView.offsetForExtraTabBarItems = YALForExtraTabBarItemsDefaultOffset
    tabBarController.tabBarView.extraTabBarItemHeight = YALExtraTabBarItemsDefaultHeight

    //Denzel Edit
    yalTabBarHeight = YALTabBarViewDefaultHeight
    //End of Denzel Edit

}
```

**Comment by serejahh** [comment]
Please, give a me link to a demo project

**Comment by IgorMuzyka** [comment]
@imanodaysoffdotcom did you set `UIAppearance` for `UIView` somewhere in your code? especially the `tintColor` value. If yes then it's the source of your problem. You can fix this by setting appearance rule for the main button or for case when it contained in it's container.

**Comment by imanodaysoffdotcom** [comment]
Thanks for the suggestion. Would you happen to have sample code for that. Is this a foldingTabBar specific hack ?

**Comment by IgorMuzyka** [comment]
@imanodaysoffdotcom nope that's not something specific for folding tab bar, but as you may notice navigation items had the same color as the main button thats why i had such an assumption about tint color.

**Comment by imanodaysoffdotcom** [comment]
So i just decided to change the background color back to the original after the alert controller is dismissed. Thanks for your help.
