### ISSUE TITLE
Error when Using Swift 3

### ISSUE THREAD

**Issue by robin43499** [Yalantis/FoldingTabBar.iOS#63]
Hi guys,

I've updated xcode to be the latest version which uses Swift 3.0. After I've converted all codes of my project and run it, I found out that 
"Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[_SwiftValue itemImage]: unrecognized selector sent to instance 0x600000056350'"

So I've debugged to find which line of code caused errors and I found this line in the library.

<img width="1140" alt="screen shot 2559-09-21 at 5 01 13 am" src="https://cloud.githubusercontent.com/assets/12056430/18698617/db3c9be4-7ff5-11e6-8f70-dd88427852d2.png">

Any Ideas to fix it???

Thanks in advance.

**Comment by serejahh** [comment]
Hi, guys. Thanks for reporting the issue!

I've added nullability directives, so now everything works properly in `1.1`

**Comment by robin43499** [comment]
Thanks !

**Comment by serejahh** [comment]
@robin43499 You're welcome. If you find any bug, report an issue 😉
