### ISSUE TITLE
Last indexed button adding itself to window when pushing view controller (iOS 10)

### ISSUE THREAD

**Issue by darranhall** [Yalantis/FoldingTabBar.iOS#64]
Hello,

We have a very specific issue with a view controller being pushed and adding the last indexed button to the main window. It won't disappear, and remains floating on top of all other elements. 

Any ideas what could be the case, or what has changed in iOS 10 that I should adapt to?

**Comment by IgorMuzyka** [comment]
@darranhall would you ming creating an example project that demonstrates the issue?

**Comment by darranhall** [comment]
Unfortunately we migrated to a native tab bar solution, but it's a simple 4 controller tab bar setup. The last view controller (right-most) should be the problem creator when pushing a view controller onto the stack. The last controller should be a UINavigationController with an embedded UITableViewController and prototyped UITableViewCells, with the UITableViewCells pushing the controllers after being tapped.
