### ISSUE TITLE
there are some errors when i run the demo,i don't know how to fix it! please help me!  thanks

### ISSUE THREAD

**Issue by qzslz** [Yalantis/FoldingTabBar.iOS#65]
[SecretBox.zip](https://github.com/Yalantis/FoldingTabBar.iOS/files/531901/SecretBox.zip)

**Comment by qzslz** [comment]
the error is          -[_SwiftValue itemImage]: unrecognized selector sent to instance     . And this occur when i set the item image for tabbaritem.If i remove these codes which set the image,and there will be nothing wrong.

**Comment by serejahh** [comment]
Hi @qzslz! Thanks for the demo project. Please, update to `1.1` version. There was a bug related to nullability directives in objective-c
