### ISSUE TITLE
Adding this project to your other existing project

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/FoldingTabBar.iOS#69]
I'm trying to add the folding tabs feature to the colormatchtabs project, could you help me out with that

**Comment by jackpaster** [comment]
i don't know how to do that

**Comment by serejahh** [comment]
Hi @jackpaster 
You can use CocoaPods. Add both dependencies and run `pod install`:
``` ruby
pod 'FoldingTabBar', '~> 1.1'
pod 'ColorMatchTabs', '~> 2.0'
```
[Read more how to use CocoaPods](https://guides.cocoapods.org/using/index.html)
