### ISSUE TITLE
How to use YALFoldingTabBarController using nib file or without using storyboard?

### ISSUE THREAD

**Issue by rahulskh** [Yalantis/FoldingTabBar.iOS#7]
How to use YALFoldingTabBarController using nib file or without using storyboard?

**Comment by rahulskh** [comment]
figured it out. thanks!

**Comment by StormFactory** [comment]
@rahulskh  Since you figured it out, it would be right to share how you did it so others who might have the same concerns can benefit.

**Comment by rahulskh** [comment]
Here is what i did. In my AppDelegate.m I modified setupYALTabBarController
- (void)setupYALTabBarController
  {
  self.window = [[UIWindow alloc] initWithFrame:[[UIScreen mainScreen] bounds]];
  
  self.view1 = [[View1 alloc] init];
  self.view2 = [[View2 alloc]init];
  self.view3 = [[View3 alloc]init];
  self.view4 = [[View4 alloc]init];
  
    NavigationController *navController1 = [[NavigationController alloc] initWithRootViewController:self.view1];
  NavigationController *navController2 = [[NavigationController alloc] initWithRootViewController:self.view2];
  NavigationController *navController3 = [[NavigationController alloc] initWithRootViewController:self.view3];
  NavigationController *navController4 = [[NavigationController alloc] initWithRootViewController:self.view4];
  
  //YALFoldingTabBarController *tabBarController = (YALFoldingTabBarController *) self.window.rootViewController;
  YALFoldingTabBarController *tabBarController = [[YALFoldingTabBarController alloc]init];
  
  //prepare leftBarItems
  YALTabBarItem *item1 = [[YALTabBarItem alloc] initWithItemImage:[UIImage imageNamed:@"Chats"]
                                                    leftItemImage:[UIImage imageNamed:@"Search"]
                                                   rightItemImage:[UIImage imageNamed:@"Cog"]];
  
  YALTabBarItem *item2 = [[YALTabBarItem alloc] initWithItemImage:[UIImage imageNamed:@"Compass"]
                                                    leftItemImage:[UIImage imageNamed:@"Chats"]
                                                   rightItemImage:[UIImage imageNamed:@"Search"]];
  
  tabBarController.leftBarItems = @[item1, item2];
  
  //prepare rightBarItems
  YALTabBarItem *item3 = [[YALTabBarItem alloc] initWithItemImage:[UIImage imageNamed:@"Group"]
                                                    leftItemImage:[UIImage imageNamed:@"Chats"]
                                                   rightItemImage:[UIImage imageNamed:@"Compass"]];
  
  YALTabBarItem *item4 = [[YALTabBarItem alloc] initWithItemImage:[UIImage imageNamed:@"Cog"]
                                                    leftItemImage:[UIImage imageNamed:@"Chats"]
                                                   rightItemImage:[UIImage imageNamed:@"Search"]];
  
  tabBarController.rightBarItems = @[item3, item4];
  
  tabBarController.centerButtonImage = [UIImage imageNamed:@"Plus"];
  
  tabBarController.selectedIndex = 2;
  
  tabBarController.viewControllers = [NSArray arrayWithObjects:navController1, navController2, navController3, navController4, nil];
  
  //customize tabBarView
  tabBarController.tabBarView.extraTabBarItemHeight = YALExtraTabBarItemsDefaultHeight;
  tabBarController.tabBarView.offsetForExtraTabBarItems = YALForExtraTabBarItemsDefaultOffset;
  tabBarController.tabBarView.backgroundColor = HEXCOLOR(0xff0066FF);
  tabBarController.tabBarView.tintColor = [UIColor whiteColor];
  tabBarController.tabBarView.tabBarColor = [UIColor colorWithRed:250.0 green:240.0 blue:230.0 alpha:1];
  tabBarController.tabBarViewHeight = YALTabBarViewDefaultHeight;
  tabBarController.tabBarView.tabBarViewEdgeInsets = YALTabBarViewHDefaultEdgeInsets;
  tabBarController.tabBarView.tabBarItemsEdgeInsets = YALTabBarViewItemsDefaultEdgeInsets;
  tabBarController.tabBarView.hidden = NO;
  
  self.window.rootViewController = tabBarController;
  [self.window makeKeyAndVisible];

}
