### ISSUE TITLE
not working in viewcontroller

### ISSUE THREAD

**Issue by knikaha** [Yalantis/FoldingTabBar.iOS#70]
i tried to avoid windows?.rootViewcontroller as? YALFoldingTabBarController 

i want to use it with viewcontroller.swift with success 

any help http://stackoverflow.com/questions/40952913/yalfoldingtabbarcontroller-not-working-with-subclasses

**Comment by serejahh** [comment]
Hi @knikaha. You can create tabbar manually or use `tabBarController` property in a view controller if you use storyboards
