### ISSUE TITLE
utilizing this in a view controller view 

### ISSUE THREAD

**Issue by jackpaster** [Yalantis/FoldingTabBar.iOS#71]
@sfes @dimazen @maximletushov @constantineSafronov @edBaev Hello I'm trying to utilize this component by adding a uiview in a view controller and simply making that view a foldingtabview. I intent for this foldingtabview to not switch between tabs but present different view controllers. But I'm having trouble with the code for that foldingtabview. what code from your project should I place in my main view controller to make the folding tab view run and seem seamless(like it already is).

**Comment by serejahh** [comment]
Hi @jackpaster! You should add the most of code from `YALFoldingTabBarController`
