### ISSUE TITLE
Actions ItemImage

### ISSUE THREAD

**Issue by resand** [Yalantis/FoldingTabBar.iOS#72]
Hi!
How he assigned actions to **_leftItemImage_** and **_rightItemImage_**

Thanks!

**Comment by jackpaster** [comment]
@resand Do you mean how do they assign actions for the left and right bar button items. Because if thats so. I have the exact same question. +1

**Comment by resand** [comment]
@jackpaster Exactly, but had not read well, you have to implement the delegate and then the methods:

**TabBarDidSelectExtraLeftItem**
**TabBarDidSelectExtraRightItem**

And so on each tab you implement the left or right icons

**Comment by Vodolazkyi** [comment]
Exactly, you should implement below methods:

`TabBarDidSelectExtraLeftItem`
`TabBarDidSelectExtraRightItem`
