### ISSUE TITLE
Memory Issue

### ISSUE THREAD

**Issue by zzz2016** [Yalantis/FoldingTabBar.iOS#75]
# Report a bug

##  What did you do?

Just click the main button, and then do it again and again and over again.

## What did you expect to happen?

The memory should not increase.

## What happened instead?

As the picture shown.

![f4477926-ddff-4f4c-b99a-a40e6ed5b2c5](https://cloud.githubusercontent.com/assets/19794679/22632261/c57c1144-ec52-11e6-9788-2f6c0cf35dc8.png)

## Your Environment

- Version of the component: latest
- iOS version: 10.1
- Device: iPhone7
- Xcode version: 8.1

## Project that demonstrates the bug

Official demo.

## My suggestion

The code below:

```
+(instancetype)animationWithKeyPath:(NSString *)keyPath
                            duration:(CFTimeInterval)duration
                             damping:(double)damping
                            velocity:(double)velocity
                           fromValue:(double)fromValue
                             toValue:(double)toValue
{
    YALSpringAnimation *animation = [self.class animationWithKeyPath:keyPath];

    **
    animation.removedOnCompletion = NO;
    animation.fillMode = kCAFillModeForwards;
    **

    animation.duration = duration;
    animation.values = [self animationValuesFromValue:fromValue
                                              toValue:toValue
                                          withDamping:damping
                                          andVelocity:velocity];
    return animation;
}

```

 The animation should be removed when finished.

**Comment by Vodolazkyi** [comment]
Problem solved in v1.1.2
