### ISSUE TITLE
unable to hide tabbarcontroller when pushed!

### ISSUE THREAD

**Issue by rahulskh** [Yalantis/FoldingTabBar.iOS#8]
unable to hide tabbarcontroller when pushed!

**Comment by StormFactory** [comment]
Did you find a solution to this?  I'm trying to hide the tabbarcontroller when EAIntroView https://github.com/ealeksandrov/EAIntroView is displayed.

**Comment by TindleWei** [comment]
I tried a clumsy way but worked.
Here is what I did:
1.  Make a globel variable **tabBarController** in AppDelegate; 
2.  Use this in every child controller of tabBarController:

```
-(void)viewWillAppear:(BOOL)animated{
    AppDelegate *appDelegate = [[UIApplication sharedApplication] delegate];
    if ([appDelegate tabBarController].tabBarView.hidden == NO) {
    } else {
        [appDelegate tabBarController].tabBarView.hidden = NO;
    }
}
```

 3.Add this in the UIViewController you pushed:

```
-(void)viewWillAppear:(BOOL)animated{
    AppDelegate *appDelegate = [[UIApplication sharedApplication] delegate];
    if ([appDelegate tabBarController].tabBarView.hidden == YES) {
    } else {
        [appDelegate tabBarController].tabBarView.hidden = YES;
    }
}
```

I know that is not a smart way, is there any other ideas ?

**Comment by rtxledo** [comment]
Any solution ? I'm stuck on this issue :(

**Comment by famAlex** [comment]
I'll follow the discussion me too!

**Comment by LarryBrian** [comment]
Basically TindleWei's answer, but less code. I did this simply by:
1. Just create a YalFoldingTabBarController property in AppDelegate.h 
   (i.e YalFoldingTabBarController *myTabBarController)
2. Import AppDelegate.h in the view controller that you want to hide the tabbarcontroller 
   (i.e #import "AppDelegate.h")
3. in ViewDidAppear method of that view controller, reference your tabBarController property in app delegate and set the tabBarView to hidden

example:
desiredViewController ()
      - (void) viewWillAppear 
           {
              AppDelegate *appDelegate = [[UIApplication sharedApplication] delegate];
              [appDelegate myTabBarController].tabBarView.hidden = YES;
           }

**Comment by Art3mS1d** [comment]
Guys, it can be done much simpler:

```
- (void)viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    YALFoldingTabBarController *tabBarController = (YALFoldingTabBarController *)self.tabBarController;
    tabBarController.tabBarView.hidden = YES;
}
```
