### ISSUE TITLE
So , it is just "wast of time" Library used in iOS 

### ISSUE THREAD

**Issue by donjin123** [Yalantis/FoldingTabBar.iOS#98]
NO Editing Permission Allow to the Developer End.
Totally Based on the Images how is working please Solve it. 
i developed same Design using the UiView().
Haaaaaaa.

**Comment by den-zv** [comment]
Hey! `FoldingTabBar.iOS` isn't a drop-in solution but is built for demonstration needs, you can feel free to use and update it to cover your needs :)
We kindly appreciate bug reports, new feature ideas and PRs with fixes / enhancements.

Closing this issue.
Please ping us back with more information in case of any solutions or problem reports.
